# Generated by Django 3.1.7 on 2021-03-31 15:58

import address.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0003_auto_20200830_1851'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('par', models.IntegerField(default=56)),
                ('slope', models.IntegerField(default=0)),
                ('holes', models.IntegerField(default=18)),
                ('location', address.models.AddressField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.address')),
            ],
        ),
        migrations.CreateModel(
            name='Hole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hole_num', models.IntegerField(default=0)),
                ('par', models.IntegerField(default=3)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('handicap', models.IntegerField(default=36)),
                ('handicap_date', models.DateTimeField(verbose_name='date')),
                ('best_round_id', models.IntegerField(null=True)),
                ('best_delta', models.IntegerField(null=True)),
                ('rounds_counted', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateTimeField(verbose_name='date')),
                ('par', models.IntegerField(default=56)),
                ('active', models.BooleanField(default=True)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scorecard.course')),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('hole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scorecard.hole')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scorecard.player')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scorecard.round')),
            ],
        ),
        migrations.CreateModel(
            name='RoundPlayers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handicap', models.IntegerField(default=36)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scorecard.player')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scorecard.round')),
            ],
        ),
        migrations.AddField(
            model_name='hole',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scorecard.round'),
        ),
        migrations.CreateModel(
            name='HistoricalHandicaps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handicap', models.IntegerField(default=36)),
                ('handicap_date', models.DateTimeField(verbose_name='date')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scorecard.player')),
            ],
        ),
    ]
