# Generated by Django 3.1.7 on 2021-04-01 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorecard', '0003_auto_20210401_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='handicap_date',
            field=models.DateTimeField(default='django.utils.timezone.now', verbose_name='date'),
        ),
    ]
