# Generated by Django 3.1.7 on 2021-04-01 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scorecard', '0005_auto_20210401_0901'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hole',
            options={'ordering': ['hole_num']},
        ),
        migrations.AlterModelOptions(
            name='score',
            options={'ordering': ['hole__hole_num']},
        ),
    ]
