# Generated by Django 3.1.7 on 2021-04-01 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scorecard', '0006_auto_20210401_1029'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='round',
            options={'ordering': ['-date']},
        ),
    ]
