# Generated by Django 3.1.7 on 2021-04-05 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scorecard', '0007_auto_20210401_1031'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roundplayers',
            options={'ordering': ['player__name']},
        ),
        migrations.AlterModelOptions(
            name='score',
            options={'ordering': ['hole__hole_num', 'player__name']},
        ),
        migrations.CreateModel(
            name='CourseHole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hole_num', models.IntegerField(default=0)),
                ('par', models.IntegerField(default=3)),
                ('distance', models.IntegerField(null=True)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scorecard.course')),
            ],
            options={
                'ordering': ['hole_num'],
            },
        ),
    ]
