# Generated by Django 3.1.7 on 2021-04-05 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorecard', '0008_auto_20210404_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='hole',
            name='distance',
            field=models.IntegerField(null=True),
        ),
    ]
