# Generated by Django 3.1.7 on 2021-04-05 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorecard', '0009_hole_distance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursehole',
            name='distance',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hole',
            name='distance',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
